version: '3'

services:
  phoenix:
    build:
      context: .
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: til_dev
      PGPORT: 5432
      PGHOST: db
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GUARDIAN_SECRET: ${GUARDIAN_SECRET}
      FRONTEND_HOST: ${FRONTEND_HOST}
      SLACK_FEED_HOOK: ${SLACK_FEED_HOOK}
      SLACK_REVIEW_HOOK: ${SLACK_REVIEW_HOOK}
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: